<a href="https://colab.research.google.com/github/shweta-todgire/Data-Science-Codes/blob/main/Feature_Scalling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded = files.upload()


Saving StudentsPerformance.csv to StudentsPerformance.csv


In [4]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

df = pd.read_csv("StudentsPerformance.csv")

feature = df["math score"].values.reshape(-1, 1)

minmax = preprocessing.MinMaxScaler()
scaled_feature = minmax.fit_transform(feature)

print(feature[:5])
print(scaled_feature[:5])

[[72]
 [69]
 [90]
 [47]
 [76]]
[[0.72]
 [0.69]
 [0.9 ]
 [0.47]
 [0.76]]


In [5]:
## Standardizing a Feature
import numpy as np
import pandas as pd
from sklearn import preprocessing

df = pd.read_csv("StudentsPerformance.csv")

feature = df.select_dtypes(include=[np.number]).values

scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature)

print("Original Feature Data:\n", feature)
print("\nStandardized Data:\n", standardized)
print("\nMean of standardized data:", standardized.mean())
print("Standard Deviation of standardized data:", standardized.std())


Original Feature Data:
 [[72 72 74]
 [69 90 88]
 [90 95 93]
 ...
 [59 71 65]
 [68 78 77]
 [77 86 86]]

Standardized Data:
 [[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 ...
 [-0.46775108  0.12547206 -0.20107904]
 [ 0.12609287  0.60515772  0.58901542]
 [ 0.71993682  1.15336989  1.18158627]]

Mean of standardized data: 5.802765675374151e-17
Standard Deviation of standardized data: 1.0


In [6]:
## RobustScaler Method
import numpy as np
import pandas as pd
from sklearn import preprocessing

df = pd.read_csv("StudentsPerformance.csv")

feature = df.select_dtypes(include=[np.number]).values

robust_scaler = preprocessing.RobustScaler()
scaled_data = robust_scaler.fit_transform(feature)

print("Original Feature Data:\n", feature)
print("\nRobust Scaled Data:\n", scaled_data)
print("\nMedian of scaled data (approx):", np.median(scaled_data))
print("IQR of scaled data (approx):", np.subtract(*np.percentile(scaled_data, [75, 25])))


Original Feature Data:
 [[72 72 74]
 [69 90 88]
 [90 95 93]
 ...
 [59 71 65]
 [68 78 77]
 [77 86 86]]

Robust Scaled Data:
 [[ 0.3         0.1         0.23529412]
 [ 0.15        1.          0.89411765]
 [ 1.2         1.25        1.12941176]
 ...
 [-0.35        0.05       -0.18823529]
 [ 0.1         0.4         0.37647059]
 [ 0.55        0.8         0.8       ]]

Median of scaled data (approx): 0.0
IQR of scaled data (approx): 1.0176470588235293


In [7]:
## Normalizing Observations
import pandas as pd
from sklearn.preprocessing import Normalizer

df = pd.read_csv("StudentsPerformance.csv")

numeric_df = df.select_dtypes(include='number')
features = numeric_df.values

normalizer_l2 = Normalizer(norm="l2")
features_l2_norm = normalizer_l2.transform(features)
print("\nL2 Normalized Features:")
print(features_l2_norm)

normalizer_l1 = Normalizer(norm="l1")
features_l1_norm = normalizer_l1.transform(features)
print("\nL1 Normalized Features:")
print(features_l1_norm)

print("\nSum of first row (L1 Norm):", features_l1_norm[0].sum())



L2 Normalized Features:
[[0.57200534 0.57200534 0.58789437]
 [0.48068745 0.62698363 0.61305066]
 [0.56059807 0.59174241 0.57928467]
 ...
 [0.52257427 0.62886056 0.57571741]
 [0.52719515 0.60472385 0.59697098]
 [0.53491573 0.59743835 0.59743835]]

L1 Normalized Features:
[[0.33027523 0.33027523 0.33944954]
 [0.27935223 0.36437247 0.3562753 ]
 [0.32374101 0.34172662 0.33453237]
 ...
 [0.3025641  0.36410256 0.33333333]
 [0.30493274 0.34977578 0.34529148]
 [0.30923695 0.34538153 0.34538153]]

Sum of first row (L1 Norm): 1.0


In [8]:
## Grouping Observations Using Clustering
import pandas as pd
from sklearn.cluster import KMeans

df = pd.read_csv("StudentsPerformance.csv")

features = df.select_dtypes(include=['float64', 'int64']).values

clusterer = KMeans(n_clusters=3, random_state=0)
clusterer.fit(features)

df["group"] = clusterer.predict(features)

print(df.head())


   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  group  
0                    none          72             72             74      0  
1               completed          69             90             88      1  
2                    none          90             95             93      1  
3                    none          47             57             44      2  
4                    none          76             78             75      1  


In [9]:
## Deleting Observations with Missing Values
import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")

clean_df = df.dropna()

print(clean_df.head())


   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  


In [10]:
## Imputing Missing Values
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

df = pd.read_csv("StudentsPerformance.csv")

features = df.select_dtypes(include=[np.number]).values

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

imputer = SimpleImputer(strategy="mean")
imputed_data = imputer.fit_transform(standardized_features)

print("True Value:", true_value)
print("Imputed Value:", imputed_data[0, 0])


True Value: 0.3900235098032764
Imputed Value: -0.0003904139237269108
